{
  "Pedidos": [
    {
      "NrCnpj": "02891567000201",
      "NrNota": "360754",
      "SerieNota": "1",
      "IdEncomenda": "24330647",
      "NrPedido": "360715",
      "DtPrevistaEntrega": "27/06/2024",
      "DtPrevistaColeta": null,
      "DtAgendamento": null,
      "Ocorrencias": [
        {
          "Codigo": "6",
          "Descricao": "Entregue",
          "Data": "26/06/2024 16:09:03",
          "CaminhoFoto": "https://tmstransportador.blob.core.windows.net/app/254/2024/06/26/comprovante/26062024_9918_2779068_24330647_1.jpg",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Indaial",
          "UF": "SC",
          "TipoRecebedor": "Outros",
          "NomeRecebedor": "Maria Clara Reis",
          "TipoDocumentoRecebedor": "CPF",
          "DocumentoRecebedor": "117.636.894-09"
        },
        {
          "Codigo": "5",
          "Descricao": "A caminho do destinatário",
          "Data": "26/06/2024 16:04:36",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Indaial",
          "UF": "SC",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "4",
          "Descricao": "Em Rota",
          "Data": "26/06/2024 16:03:27",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Indaial",
          "UF": "SC",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "3",
          "Descricao": "Geração de lista",
          "Data": "26/06/2024 16:02:36",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Indaial",
          "UF": "SC",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "15",
          "Descricao": "Transferido",
          "Data": "26/06/2024 09:48:38",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Indaial",
          "UF": "SC",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "14",
          "Descricao": "Em Transferência",
          "Data": "26/06/2024 08:11:26",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Blumenau",
          "UF": "SC",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "15",
          "Descricao": "Transferido",
          "Data": "26/06/2024 00:02:08",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Blumenau",
          "UF": "SC",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "14",
          "Descricao": "Em Transferência",
          "Data": "25/06/2024 22:31:55",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Curitiba",
          "UF": "PR",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "2",
          "Descricao": "Recebido pela transportadora",
          "Data": "25/06/2024 10:36:43",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Curitiba",
          "UF": "PR",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        },
        {
          "Codigo": "1",
          "Descricao": "Arquivo Recebido",
          "Data": "25/06/2024 10:36:43",
          "CaminhoFoto": "",
          "CaminhoAssinatura": "",
          "Motorista": "",
          "Placa": "",
          "Cidade": "Curitiba",
          "UF": "PR",
          "TipoRecebedor": "",
          "NomeRecebedor": "",
          "TipoDocumentoRecebedor": "",
          "DocumentoRecebedor": ""
        }
      ]
    }
  ]
}
